services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - brand-dashboard-net

  backend:
    build: ./backend
    container_name: brand-dashboard-backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo
    networks:
      - brand-dashboard-net

  frontend:
    build: ./frontend
    container_name: brand-dashboard-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - brand-dashboard-net

  trino:
    image: trinodb/trino:435
    container_name: trino
    ports:
      - "8090:8080"
    volumes:
      - ./trino/catalog:/etc/trino/catalog
    networks:
      - brand-dashboard-net

  superset-db:
    image: postgres:13-alpine
    container_name: superset-db
    environment:
      - POSTGRES_DB=superset
      - POSTGRES_USER=superset
      - POSTGRES_PASSWORD=superset
    volumes:
      - superset-postgres-data:/var/lib/postgresql/data
    networks:
      - brand-dashboard-net

  superset:
    build: ./superset
    container_name: superset
    expose:
      - "8088"
    depends_on:
      - trino
      - mongo
      - superset-db
    environment:
      - SUPERSET_SECRET_KEY=jwt.secret=86251ab13a12de28439018414f2441dedac2d6ff52cd61ff9d625e862e41dad2
      - SUPERSET_GUEST_TOKEN_JWT_SECRET=hiUasToS3ihDkBhBTyRB3trC1v9SzWH_nWJehi5B2tI
      - SUPERSET_LOAD_EXAMPLES=no
      - SUPERSET_CONFIG_PATH=/app/superset_config.py
      - PYTHONPATH=/app
      - ADMIN_USERNAME=admin
      - ADMIN_EMAIL=admin@admin.com
      - ADMIN_PASSWORD=admin
      - TRINO_HOST=trino
      - TRINO_PORT=8080
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - SUPERSET_DATABASE_URL=postgresql://superset:superset@superset-db:5432/superset
      # Force X-Frame-Options to allow iframe embedding
      - SUPERSET_X_FRAME_OPTIONS=ALLOWALL
      - SUPERSET_FRAME_PROTECTION=false
    volumes:
      - ./superset/superset_config.py:/app/superset_config.py
      - ./superset/superset_init.sh:/app/superset_init.sh
      - superset-data:/var/lib/superset
      - superset-db:/app/superset.db
    networks:
      - brand-dashboard-net

  superset-proxy:
    image: nginx:alpine
    container_name: superset-proxy
    ports:
      - "8088:80"
    volumes:
      - ./superset/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - superset
    networks:
      - brand-dashboard-net


volumes:
  mongo-data:
  superset-data:
  superset-db:
  superset-postgres-data:

networks:
  brand-dashboard-net:
    driver: bridge
